### ISSUE TITLE
Let's simplify

### ISSUE THREAD

**Issue by istx25** [cosmiclabsio/cosmiclabsio.github.io#3]
@mcansh: Sorry for not working on this much. We've been pretty busy with other work. I have a few tasks that I would like to see finished at some point, but take your time. :smile: 
### Tasks
- [x] Comment out "WORKS" link temporarily (as we do not have a portfolio yet)
- [x] Remove all webpages/code related to the "[LABS](http://cosmiclabsio.github.io/labs)" link. We've abandoned this idea.
- [x] Add `mailto:general@cosmiclabs.io` to "CONTACT" link.
- [x] Remove "HOME" link. It's no longer necessary.

I'd also love it if you could get in touch with me so we can start designing/planning out the hiring page.

Thanks. :+1:

**Comment by istx25** [comment]
@mcansh: Also, a few more things that I would like to see (if possible!)
- [x] Add "GITHUB" link to bottom menu.
- [x] **EXPERIMENTAL**: Move team pictures ([image](https://cloud.githubusercontent.com/assets/6799989/9126491/8a531904-3ca5-11e5-8614-79988146411e.png)) to the right of the "start your project" button.
